version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    labels:
      - "dependencies"
    commit-message:
      prefix: "feat"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
